title: Grav
author:
  name: Joe villags
  email: 'joe@test.com'
villa:
  route: ''
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'

taxonomies: [category,tag,month]
redirects:
    /changelog: /villa/the-urban-jungle
routes:
    /something/else: /villa/focus-and-blur
    /another/one/(.*): /villa/$1

