title: Luxury Villas in Italy               # Name of the site
default_lang: en                            # Default language for site (potentially used by theme)

author:
  name: Daniel Wrightson                    # Default author name
  email: 'dan@invitationto.com'             # Default author email

taxonomies: [category,tag,type]             # Arbitrary list of taxonomy types

metadata:
  description: 'Luxury Villas in Italy'     # Site description

summary:
  enabled: true                             # enable or disable summary of page
  format: short                             # long = summary delimiter will be ignored; short = use the first occurrence of delimiter or size
  size: 300                                 # Maximum length of summary (characters)
  delimiter: ===                            # The summary delimiter

redirects:
#  '/redirect-test': '/'                         # Redirect test goes to home page
#  '/old/(.*)': '/new/$1'                        # Would redirect /old/my-page to /new/my-page

routes:
#  '/something/else': '/villa/sample-3'         # Alias for /villa/sample-3
#  '/new/(.*)': '/villa/$1'                     # Regex any /new/my-page URL to /villa/my-page Route

villa:
  route: '/villa'                            # Custom value added (accessible via system.villa.route)

#menu:                                      # Sample Menu Example
#    - text: Source
#      icon: github
#      url: https://github.com/getgrav/grav
#    - icon: twitter
#      url: http://twitter.com/getgrav
